#!/usr/bin/env bash
# ESPS3 bridge installer. Run from the repo root:
#   tools/install.sh             # normal install
#   tools/install.sh --autostart # + register launchd agents for USB + BLE
#                                # so the board gets data on login whichever
#                                # way it's plugged in
#   tools/install.sh --uninstall # remove wrappers + launchd agents + venv
#
# Does NOT flash the board. Use `pio run -t upload` from a dev machine for that.

set -euo pipefail

# ── Where things live ────────────────────────────────────────────────
REPO="$(cd "$(dirname "$0")/.." && pwd)"
ESPS3_HOME="$HOME/.esps3"
VENV="$ESPS3_HOME/venv"
BIN="$ESPS3_HOME/bin"
LOG="$ESPS3_HOME/log"
LA="$HOME/Library/LaunchAgents"
PLIST_USB="$LA/com.esps3.bridge.usb.plist"
PLIST_BLE="$LA/com.esps3.bridge.ble.plist"
PLIST_LEGACY="$LA/com.esps3.bridge.plist"
STATUSLINE="$HOME/.claude/statusline.sh"

AUTOSTART=0
UNINSTALL=0
SKIP_PATCH=0
for arg in "$@"; do
  case "$arg" in
    --autostart)   AUTOSTART=1 ;;
    --uninstall)   UNINSTALL=1 ;;
    --no-patch)    SKIP_PATCH=1 ;;
    -h|--help)
      sed -n '2,10p' "$0" | sed 's/^# //'
      exit 0
      ;;
    *) echo "unknown flag: $arg" >&2; exit 1 ;;
  esac
done

say()  { printf '\033[1;36m[esps3]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[esps3]\033[0m %s\n' "$*"; }
err()  { printf '\033[1;31m[esps3]\033[0m %s\n' "$*" >&2; }

unload_if_present() {
  local plist="$1"
  [ -f "$plist" ] || return 0
  launchctl unload "$plist" 2>/dev/null || true
}

# ── Uninstall path ───────────────────────────────────────────────────
if [ "$UNINSTALL" = 1 ]; then
  for p in "$PLIST_USB" "$PLIST_BLE" "$PLIST_LEGACY"; do
    if [ -f "$p" ]; then
      say "unloading $(basename "$p")"
      unload_if_present "$p"
      rm -f "$p"
    fi
  done
  if [ -d "$ESPS3_HOME" ]; then
    say "removing $ESPS3_HOME"
    rm -rf "$ESPS3_HOME"
  fi
  say "done. (shell PATH export stays in ~/.zshrc; remove by hand if you want)"
  exit 0
fi

# ── Prereq checks ────────────────────────────────────────────────────
need_cmd() {
  command -v "$1" >/dev/null 2>&1 || { err "missing: $1 — $2"; exit 1; }
}
need_cmd python3 "install Python 3 (brew install python@3)"
if ! command -v mole >/dev/null 2>&1; then
  if command -v brew >/dev/null 2>&1; then
    say "installing mole via homebrew tap"
    brew install tw93/tap/mole
  else
    err "mole not installed and homebrew is missing. install mole manually first."
    err "see https://github.com/tw93/Mole"
    exit 1
  fi
fi
say "mole:      $(command -v mole)"
say "python3:   $(command -v python3) ($(python3 -V 2>&1))"
say "repo:      $REPO"

# ── Create venv + deps ───────────────────────────────────────────────
mkdir -p "$BIN" "$LOG"
if [ ! -d "$VENV" ]; then
  say "creating venv at $VENV"
  python3 -m venv "$VENV"
fi
say "installing python deps (pyserial, Pillow, bleak) into venv"
"$VENV/bin/pip" install --quiet --upgrade pip
"$VENV/bin/pip" install --quiet pyserial Pillow bleak

# ── Wrapper scripts ──────────────────────────────────────────────────
cat > "$BIN/esps3-bridge" <<EOF
#!/bin/bash
# Auto-generated by tools/install.sh — do not edit by hand.
exec "$VENV/bin/python3" "$REPO/tools/mole-bridge.py" "\$@"
EOF
chmod +x "$BIN/esps3-bridge"

cat > "$BIN/esps3-bridge-ble" <<EOF
#!/bin/bash
# Auto-generated by tools/install.sh — do not edit by hand.
exec "$VENV/bin/python3" "$REPO/tools/mole-bridge-ble.py" "\$@"
EOF
chmod +x "$BIN/esps3-bridge-ble"

cat > "$BIN/esps3-shot" <<EOF
#!/bin/bash
# Auto-generated by tools/install.sh — do not edit by hand.
exec "$VENV/bin/python3" "$REPO/tools/shot.py" "\$@"
EOF
chmod +x "$BIN/esps3-shot"

say "wrappers installed:"
printf "   %s\n   %s\n   %s\n" \
  "$BIN/esps3-bridge" "$BIN/esps3-bridge-ble" "$BIN/esps3-shot"

# ── Ensure PATH export in ~/.zshrc ───────────────────────────────────
ZSHRC="$HOME/.zshrc"
if ! grep -q '\.esps3/bin' "$ZSHRC" 2>/dev/null; then
  printf '\n# ESPS3 bridge commands\nexport PATH="$HOME/.esps3/bin:$PATH"\n' \
    >> "$ZSHRC"
  say "added ~/.esps3/bin to PATH in ~/.zshrc (open a new shell to pick it up)"
fi

# ── Patch ~/.claude/statusline.sh to cache context_window ────────────
if [ "$SKIP_PATCH" = 0 ]; then
  if [ -f "$STATUSLINE" ]; then
    if grep -q 'context_window: .context_window' "$STATUSLINE"; then
      say "statusline.sh already patched"
    else
      say "patching $STATUSLINE (backup saved)"
      cp "$STATUSLINE" "$STATUSLINE.bak.$(date +%Y%m%d%H%M%S)"
      # 1. always write the cache when there's any input
      sed -i '' \
        's|if \[ "\${live_five_pct:-}" != "null" \] && \[ -n "\${live_five_pct:-}" \] && \[ -n "\$input" \]; then|if [ -n "$input" ]; then|' \
        "$STATUSLINE"
      # 2. include context_window + cached_at alongside rate_limits
      sed -i '' \
        "s|jq '{rate_limits: \.rate_limits}'|jq '{rate_limits: .rate_limits, context_window: .context_window, cached_at: (now \| floor)}'|" \
        "$STATUSLINE"
    fi
  else
    warn "no ~/.claude/statusline.sh found; skipping patch"
    warn "  (you'll need Claude Code's statusline feature + the patch described"
    warn "   in docs/05-mole-dashboard.md for Claude data to show up)"
  fi
fi

# ── launchd autostart (optional) ─────────────────────────────────────
write_plist() {
  local path="$1" label="$2" program="$3" stem="$4"
  cat > "$path" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$label</string>
  <key>ProgramArguments</key>
  <array>
    <string>$program</string>
    <string>--interval</string><string>2</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>ThrottleInterval</key><integer>5</integer>
  <key>StandardOutPath</key><string>$LOG/$stem.out</string>
  <key>StandardErrorPath</key><string>$LOG/$stem.err</string>
  <key>EnvironmentVariables</key>
  <dict>
    <!-- mole needs /usr/sbin (system_profiler) and /sbin (sysctl) to read
         model / cpu_model / uptime_seconds. -->
    <key>PATH</key><string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
  </dict>
</dict>
</plist>
EOF
}

if [ "$AUTOSTART" = 1 ]; then
  # Remove any v1 single-agent plist so we don't end up with two USB bridges.
  if [ -f "$PLIST_LEGACY" ]; then
    say "removing legacy $(basename "$PLIST_LEGACY")"
    unload_if_present "$PLIST_LEGACY"
    rm -f "$PLIST_LEGACY"
  fi

  mkdir -p "$LA"

  say "writing launchd agents (USB + BLE)"
  write_plist "$PLIST_USB" "com.esps3.bridge.usb" \
              "$BIN/esps3-bridge"      "bridge-usb"
  write_plist "$PLIST_BLE" "com.esps3.bridge.ble" \
              "$BIN/esps3-bridge-ble"  "bridge-ble"

  for p in "$PLIST_USB" "$PLIST_BLE"; do
    launchctl unload "$p" 2>/dev/null || true
    launchctl load "$p"
  done

  say "autostart enabled. both bridges are running under launchd."
  say "logs:"
  say "  USB:  tail -f $LOG/bridge-usb.out   $LOG/bridge-usb.err"
  say "  BLE:  tail -f $LOG/bridge-ble.out   $LOG/bridge-ble.err"
  say "disable one: launchctl unload <plist>"

  # First-time-BLE: macOS pops a permission prompt the first time Python
  # touches CoreBluetooth. If launchd started the BLE bridge before the
  # user granted it, subsequent runs might silently fail to scan.
  warn "first BLE run may trigger a macOS Bluetooth permission prompt."
  warn "  if the BLE bridge log shows 'no ESPS3 boards seen' indefinitely,"
  warn "  open System Settings -> Privacy & Security -> Bluetooth and"
  warn "  enable the python3 entry, then:"
  warn "    launchctl kickstart -k gui/\$(id -u)/com.esps3.bridge.ble"
fi

# ── Post-install summary ─────────────────────────────────────────────
cat <<EOF

$(say "install complete.")

Plug the board in; its USB VID 303A:1001 will be auto-detected.

Quick commands (available after you start a new shell, or run them with
the full path today):
    $BIN/esps3-bridge              # USB bridge (foreground)
    $BIN/esps3-bridge-ble          # BLE bridge (foreground)
    $BIN/esps3-shot                # capture /tmp/esps3-shot.png
EOF

if [ "$AUTOSTART" = 1 ]; then
  cat <<EOF

Both launchd agents are active — they start at login and respawn if they
crash. Whichever path has the board connected at any given moment wins
on the display. Logs:
    tail -f $LOG/bridge-usb.out
    tail -f $LOG/bridge-ble.out
EOF
else
  cat <<EOF

To install the launchd autostart agents too, run:
    tools/install.sh --autostart
EOF
fi
