#!/usr/bin/env bash
# ESPS3 bridge installer. Run from the repo root:
#   tools/install.sh             # normal install
#   tools/install.sh --autostart # + register launchd agent so the bridge
#                                # starts automatically at login
#   tools/install.sh --uninstall # remove wrappers + launchd agent + venv
#
# Does NOT flash the board. Use `pio run -t upload` from a dev machine for that.

set -euo pipefail

# ── Where things live ────────────────────────────────────────────────
REPO="$(cd "$(dirname "$0")/.." && pwd)"
ESPS3_HOME="$HOME/.esps3"
VENV="$ESPS3_HOME/venv"
BIN="$ESPS3_HOME/bin"
LOG="$ESPS3_HOME/log"
PLIST="$HOME/Library/LaunchAgents/com.esps3.bridge.plist"
STATUSLINE="$HOME/.claude/statusline.sh"

AUTOSTART=0
UNINSTALL=0
SKIP_PATCH=0
for arg in "$@"; do
  case "$arg" in
    --autostart)   AUTOSTART=1 ;;
    --uninstall)   UNINSTALL=1 ;;
    --no-patch)    SKIP_PATCH=1 ;;
    -h|--help)
      sed -n '2,10p' "$0" | sed 's/^# //'
      exit 0
      ;;
    *) echo "unknown flag: $arg" >&2; exit 1 ;;
  esac
done

say()  { printf '\033[1;36m[esps3]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[esps3]\033[0m %s\n' "$*"; }
err()  { printf '\033[1;31m[esps3]\033[0m %s\n' "$*" >&2; }

# ── Uninstall path ───────────────────────────────────────────────────
if [ "$UNINSTALL" = 1 ]; then
  if [ -f "$PLIST" ]; then
    say "unloading launchd agent"
    launchctl unload "$PLIST" 2>/dev/null || true
    rm -f "$PLIST"
  fi
  if [ -d "$ESPS3_HOME" ]; then
    say "removing $ESPS3_HOME"
    rm -rf "$ESPS3_HOME"
  fi
  say "done. (shell PATH export stays in ~/.zshrc; remove by hand if you want)"
  exit 0
fi

# ── Prereq checks ────────────────────────────────────────────────────
need_cmd() {
  command -v "$1" >/dev/null 2>&1 || { err "missing: $1 — $2"; exit 1; }
}
need_cmd python3 "install Python 3 (brew install python@3)"
if ! command -v mole >/dev/null 2>&1; then
  if command -v brew >/dev/null 2>&1; then
    say "installing mole via homebrew tap"
    brew install tw93/tap/mole
  else
    err "mole not installed and homebrew is missing. install mole manually first."
    err "see https://github.com/tw93/Mole"
    exit 1
  fi
fi
say "mole:      $(command -v mole)"
say "python3:   $(command -v python3) ($(python3 -V 2>&1))"
say "repo:      $REPO"

# ── Create venv + deps ───────────────────────────────────────────────
mkdir -p "$BIN" "$LOG"
if [ ! -d "$VENV" ]; then
  say "creating venv at $VENV"
  python3 -m venv "$VENV"
fi
say "installing python deps (pyserial, Pillow) into venv"
"$VENV/bin/pip" install --quiet --upgrade pip
"$VENV/bin/pip" install --quiet pyserial Pillow

# ── Wrapper scripts ──────────────────────────────────────────────────
cat > "$BIN/esps3-bridge" <<EOF
#!/bin/bash
# Auto-generated by tools/install.sh — do not edit by hand.
exec "$VENV/bin/python3" "$REPO/tools/mole-bridge.py" "\$@"
EOF
chmod +x "$BIN/esps3-bridge"

cat > "$BIN/esps3-shot" <<EOF
#!/bin/bash
# Auto-generated by tools/install.sh — do not edit by hand.
exec "$VENV/bin/python3" "$REPO/tools/shot.py" "\$@"
EOF
chmod +x "$BIN/esps3-shot"

say "wrappers installed:"
printf "   %s\n   %s\n" "$BIN/esps3-bridge" "$BIN/esps3-shot"

# ── Ensure PATH export in ~/.zshrc ───────────────────────────────────
ZSHRC="$HOME/.zshrc"
if ! grep -q '\.esps3/bin' "$ZSHRC" 2>/dev/null; then
  printf '\n# ESPS3 bridge commands\nexport PATH="$HOME/.esps3/bin:$PATH"\n' \
    >> "$ZSHRC"
  say "added ~/.esps3/bin to PATH in ~/.zshrc (open a new shell to pick it up)"
fi

# ── Patch ~/.claude/statusline.sh to cache context_window ────────────
if [ "$SKIP_PATCH" = 0 ]; then
  if [ -f "$STATUSLINE" ]; then
    if grep -q 'context_window: .context_window' "$STATUSLINE"; then
      say "statusline.sh already patched"
    else
      say "patching $STATUSLINE (backup saved)"
      cp "$STATUSLINE" "$STATUSLINE.bak.$(date +%Y%m%d%H%M%S)"
      # 1. always write the cache when there's any input
      sed -i '' \
        's|if \[ "\${live_five_pct:-}" != "null" \] && \[ -n "\${live_five_pct:-}" \] && \[ -n "\$input" \]; then|if [ -n "$input" ]; then|' \
        "$STATUSLINE"
      # 2. include context_window + cached_at alongside rate_limits
      sed -i '' \
        "s|jq '{rate_limits: \.rate_limits}'|jq '{rate_limits: .rate_limits, context_window: .context_window, cached_at: (now \| floor)}'|" \
        "$STATUSLINE"
    fi
  else
    warn "no ~/.claude/statusline.sh found; skipping patch"
    warn "  (you'll need Claude Code's statusline feature + the patch described"
    warn "   in docs/05-mole-dashboard.md for Claude data to show up)"
  fi
fi

# ── launchd autostart (optional) ─────────────────────────────────────
if [ "$AUTOSTART" = 1 ]; then
  say "writing launchd agent at $PLIST"
  mkdir -p "$(dirname "$PLIST")"
  cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>com.esps3.bridge</string>
  <key>ProgramArguments</key>
  <array>
    <string>$BIN/esps3-bridge</string>
    <string>--interval</string><string>2</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>ThrottleInterval</key><integer>5</integer>
  <key>StandardOutPath</key><string>$LOG/bridge.out</string>
  <key>StandardErrorPath</key><string>$LOG/bridge.err</string>
  <key>EnvironmentVariables</key>
  <dict>
    <!-- mole needs /usr/sbin (system_profiler) and /sbin (sysctl) to read
         model / cpu_model / uptime_seconds. -->
    <key>PATH</key><string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
  </dict>
</dict>
</plist>
EOF
  launchctl unload "$PLIST" 2>/dev/null || true
  launchctl load "$PLIST"
  say "autostart enabled. bridge is running under launchd now."
  say "logs:      tail -f $LOG/bridge.out   $LOG/bridge.err"
  say "disable:   launchctl unload $PLIST"
fi

# ── Post-install summary ─────────────────────────────────────────────
cat <<EOF

$(say "install complete.")

Plug the board in; its USB VID 303A:1001 will be auto-detected.

Quick commands (available after you start a new shell, or run them with
the full path today):
    $BIN/esps3-bridge              # run bridge in foreground
    $BIN/esps3-shot                # capture /tmp/esps3-shot.png
EOF

if [ "$AUTOSTART" = 1 ]; then
  cat <<EOF

The launchd agent is active — the bridge will start automatically at
every login and respawn if it crashes. Follow its logs with:
    tail -f $LOG/bridge.out
EOF
else
  cat <<EOF

To install the launchd autostart agent too, run:
    tools/install.sh --autostart
EOF
fi
